name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start xcodebuild test
      run: xcodebuild clean test -project "Calculator SwiftUI.xcodeproj" -scheme "Calculator SwiftUI" -destination "platform=iOS Simulator,name=iPhone 8"
